### ISSUE TITLE
Implement PAIN Exporter

### ISSUE THREAD

**Issue by lukasbischof** [stiftungswo/betterIzivi#14]
Add a Service which generates the PAIN payment XML

**Comment by TheFehr** [comment]
Waiting for salesking/sepa_king#90 and need more info from Marc and/or Andi

**Comment by skius** [comment]
Momentane Ansicht für Auszahlung beibehalten, evtl. ohne Payment-Tabelle realisierbar mithilfe von payment_executed Feld auf ExpenseSheet?
